//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant.Models
{
    using Microsoft.Ajax.Utilities;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Invoices
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Invoices()
        {
            this.InvoiceDetails = new HashSet<InvoiceDetails>();
        }

        [DisplayName("Invoice Number")]
        public string InvID { get; set; }

        [DisplayName("Invoice Time")]
        public System.DateTime InvoiceTime { get; set; }
        public double Total { get; set; }

        [DisplayName("Tips Amount")]
        public double Tips { get; set; }

        [DisplayName("Payment Method")]
        public short PaymentID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceDetails> InvoiceDetails { get; set; }
        public virtual PayMethods PayMethods { get; set; }
    }
}
