//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class InvoiceDetails
    {
        public long SSN { get; set; }

        [DisplayName("Invoice Number")]
        public string InvID { get; set; }

        [DisplayName("Order Number")]
        public string OrderID { get; set; }

        public double SubTotal { get; set; }
    
        public virtual Invoices Invoices { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
