//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Items
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Items()
        {
            this.OrderDetails = new HashSet<OrderDetails>();
        }

        [Required(ErrorMessage = "Item Number is required")]
        [DisplayName("Item Number")]
        public short ItemID { get; set; }

        [Required(ErrorMessage = "Category Number is required")]
        [DisplayName("Category Number")]
        public short CatID { get; set; }

        [Required(ErrorMessage = "Item Name is required")]
        [DisplayName("Item Name")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Item Code is required")]
        [DisplayName("Item Code")]
        public string DishCode { get; set; }

        [Required(ErrorMessage = "Price is required")]
        public double Price { get; set; }

        [Required(ErrorMessage = "Description is required")]
        public string Description { get; set; }
        public byte[] Photo { get; set; }

        [Required(ErrorMessage = "Section Number is required")]
        [DisplayName("Section Number")]
        public short SecID { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual WorkSections WorkSections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetails> OrderDetails { get; set; }
    }
}
