//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class OrderDetails
    {
        public long SSN { get; set; }

        [DisplayName("Order Number")]
        public string OrderID { get; set; }

        [DisplayName("Item Number")]
        public short ItemID { get; set; }

        [DisplayName("Order Time")]
        public System.DateTime OrderTime { get; set; }
        
        public bool Preparing { get; set; }

        [DisplayName("Preparing Time")]
        public Nullable<System.DateTime> PreTime { get; set; }

        public bool Served { get; set; }

        [DisplayName("Served Time")]
        public Nullable<System.DateTime> ServedTime { get; set; }

        public bool Paid { get; set; }

        [DisplayName("Paid Time")]
        public Nullable<System.DateTime> PaidTime { get; set; }

        [DisplayName("Invoice Group")]
        public byte InvoiceGrp { get; set; }
    
        public virtual Items Items { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
