//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.InvoiceDetails = new HashSet<InvoiceDetails>();
            this.OrderDetails = new HashSet<OrderDetails>();
        }

        [DisplayName("Order Number")]
        public string OrderID { get; set; }

        [DisplayName("Order Time")]
        public System.DateTime TableTime { get; set; }

        [DisplayName("Table Number")]
        public short TbID { get; set; }

        [DisplayName("Paid Status")]
        public bool AllPaid { get; set; }

        [DisplayName("Paid Time")]
        public Nullable<System.DateTime> AllPaidTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceDetails> InvoiceDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetails> OrderDetails { get; set; }
        public virtual Tables Tables { get; set; }
    }
}
